// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caiunqdrzjlltaeaexqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhaXVucWRyempsbHRhZWFleHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTQ2NjksImV4cCI6MjA3MTI3MDY2OX0.q8Dk87I4TbxXvV-Czfkpt5yw6g7NeINp6Fv8rc8qBVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});